# Generated by Django 3.1.1 on 2020-09-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0003_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=10)),
                ('tag', models.ManyToManyField(related_name='post_tag_realtion', to='drf.Tag')),
            ],
        ),
    ]
