# Generated by Django 3.1.1 on 2020-09-27 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0005_school_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='drf.user')),
                ('phone', models.CharField(max_length=10)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(max_length=7)),
                ('userimage', models.ImageField(upload_to='UserImage/')),
            ],
        ),
    ]
