# Generated by Django 3.1.1 on 2020-09-27 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0006_userdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
