# Generated by Django 3.1.1 on 2020-09-22 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('phone', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'UserDetail',
                'verbose_name_plural': 'UserDetails',
                'db_table': 'UserDetail',
                'managed': True,
            },
        ),
    ]
