# Generated by Django 3.1.1 on 2020-09-22 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf_router', '0004_auto_20200922_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='post',
        ),
    ]
