# Generated by Django 3.1.1 on 2020-09-22 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf_router', '0005_auto_20200922_1408'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
