# Generated by Django 3.1.1 on 2020-09-22 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf_router', '0007_comment_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
